In [41]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('book1.csv')
df

,UID,Bachelor of Science in Civil Engineering,Bachelor of Science in Electrical Engineering,Bachelor of Science in Information Technology,Bachelor of Science in Computer Science,Bachelor of Science in Library and Information Science,Bachelor of Science in Accountancy,Bachelor of Science in Management Accounting,Bachelor of Science in internal Auditing,Bachelor of Science in Business Administration,Bachelor of Science in Psychology,Bachelor of Physical Education,Bachelor of Elementary Education,Bachelor of Secondary Education,Bachelor of Special Needs Education,Bachelor in Human Needs,Bachelor of Science in Hospital Management,Bachelor of Science in Nursing
0,UID1,3,3,3,3,3,3,3,1,3,4,2,3,2,3,4,3,3
1,UID2,4,5,3,3,4,1,2,5,5,5,2,3,2,3,3,2,1
2,UID3,4,4,4,5,4,1,3,2,3,4,1,3,3,3,2,3,4
3,UID4,3,5,4,3,5,3,3,3,4,3,1,3,2,3,2,5,3
4,UID5,2,2,3,2,4,4,3,3,4,4,3,4,3,2,2,4,3
5,UID6,1,1,2,1,1,1,1,1,1,1,1,1,1,2,1,1,1
6,UID7,2,2,4,4,3,2,2,1,3,3,3,3,3,2,3,3,2
7,UID8,4,3,5,5,4,3,5,4,4,4,4,4,4,5,4,4,5
8,UID9,2,3,3,5,2,3,2,4,5,4,4,4,1,3,3,4,4
9,UID10,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3
10,UID11,5,3,5,4,3,2,2,2,3,4,3,3,3,3,3,3,3
11,UID12,1,1,1,1,1,1,1,1,1,1,1,1,4,1,1,1,1
12,UID13,1,1,5,3,1,1,1,1,1,3,3,1,1,1,1,4,4
13,UID14,3,2,4,2,2,4,3,4,2,2,2,3,3,3,3,4,4
14,UID15,2,2,3,3,2,3,3,4,3,4,3,4,4,3,3,3,2
15,UID16,3,3,2,2,3,3,3,3,3,4,4,4,4,4,3,4,3
16,UID17,3,3,2,2,2,3,4,3,4,3,3,2,3,3,3,4,4
17,UID18,5,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
18,UID19,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [42]:
corrMatrix = df.corr(method='pearson')
corrMatrix.head(17)

C:\Users\acer\AppData\Local\Temp\ipykernel_7060\2951496345.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corrMatrix = df.corr(method='pearson')

,Bachelor of Science in Civil Engineering,Bachelor of Science in Electrical Engineering,Bachelor of Science in Information Technology,Bachelor of Science in Computer Science,Bachelor of Science in Library and Information Science,Bachelor of Science in Accountancy,Bachelor of Science in Management Accounting,Bachelor of Science in internal Auditing,Bachelor of Science in Business Administration,Bachelor of Science in Psychology,Bachelor of Physical Education,Bachelor of Elementary Education,Bachelor of Secondary Education,Bachelor of Special Needs Education,Bachelor in Human Needs,Bachelor of Science in Hospital Management,Bachelor of Science in Nursing
Bachelor of Science in Civil Engineering,1.000000,0.403328,0.071788,0.190073,0.336830,-0.027430,0.255546,0.179182,0.194143,0.180021,-0.062487,0.144252,0.022912,0.319628,0.284448,-0.070085,0.061726
Bachelor of Science in Electrical Engineering,0.403328,1.000000,0.325025,0.516855,0.831356,0.195610,0.501678,0.566590,0.786681,0.687130,0.058379,0.536590,0.112267,0.634457,0.511052,0.443093,0.272029
Bachelor of Science in Information Technology,0.071788,0.325025,1.000000,0.731853,0.470053,0.184812,0.335449,0.203496,0.285364,0.504012,0.340700,0.388073,0.076932,0.386151,0.373388,0.603672,0.634142
Bachelor of Science in Computer Science,0.190073,0.516855,0.731853,1.000000,0.524470,0.118971,0.414193,0.312717,0.586431,0.684341,0.448804,0.591201,0.109055,0.543774,0.549521,0.476801,0.603219
Bachelor of Science in Library and Information Science,0.336830,0.831356,0.470053,0.524470,1.000000,0.356239,0.611602,0.445101,0.722272,0.683898,0.126239,0.675053,0.302072,0.608351,0.490558,0.520706,0.318301
Bachelor of Science in Accountancy,-0.027430,0.195610,0.184812,0.118971,0.356239,1.000000,0.693382,0.516597,0.475283,0.348694,0.514255,0.698232,0.369540,0.530562,0.608262,0.700318,0.524807
Bachelor of Science in Management Accounting,0.255546,0.501678,0.335449,0.414193,0.611602,0.693382,1.000000,0.564956,0.601398,0.536333,0.445294,0.677588,0.569976,0.834794,0.737359,0.638663,0.669783
Bachelor of Science in internal Auditing,0.179182,0.566590,0.203496,0.312717,0.445101,0.516597,0.564956,1.000000,0.728785,0.575086,0.428454,0.682951,0.286333,0.659137,0.540675,0.450456,0.315148
Bachelor of Science in Business Administration,0.194143,0.786681,0.285364,0.586431,0.722272,0.475283,0.601398,0.728785,1.000000,0.793857,0.477674,0.766205,0.167717,0.651562,0.669417,0.554095,0.371932
Bachelor of Science in Psychology,0.180021,0.687130,0.504012,0.684341,0.683898,0.348694,0.536333,0.575086,0.793857,1.000000,0.587195,0.783437,0.267725,0.638095,0.691912,0.538086,0.433363
Bachelor of Physical Education,-0.062487,0.058379,0.340700,0.448804,0.126239,0.514255,0.445294,0.428454,0.477674,0.587195,1.000000,0.619595,0.308673,0.510252,0.603286,0.554454,0.535857
Bachelor of Elementary Education,0.144252,0.536590,0.388073,0.591201,0.675053,0.698232,0.677588,0.682951,0.766205,0.783437,0.619595,1.000000,0.467806,0.758420,0.754224,0.613241,0.451118
Bachelor of Secondary Education,0.022912,0.112267,0.076932,0.109055,0.302072,0.369540,0.569976,0.286333,0.167717,0.267725,0.308673,0.467806,1.000000,0.464356,0.419184,0.194871,0.182325
Bachelor of Special Needs Education,0.319628,0.634457,0.386151,0.543774,0.608351,0.530562,0.834794,0.659137,0.651562,0.638095,0.510252,0.758420,0.464356,1.000000,0.815307,0.530311,0.560039
Bachelor in Human Needs,0.284448,0.511052,0.373388,0.549521,0.490558,0.608262,0.737359,0.540675,0.669417,0.691912,0.603286,0.754224,0.419184,0.815307,1.000000,0.466204,0.464108
Bachelor of Science in Hospital Management,-0.070085,0.443093,0.603672,0.476801,0.520706,0.700318,0.638663,0.450456,0.554095,0.538086,0.554454,0.613241,0.194871,0.530311,0.466204,1.000000,0.814875
Bachelor of Science in Nursing,0.061726,0.272029,0.634142,0.603219,0.318301,0.524807,0.669783,0.315148,0.371932,0.433363,0.535857,0.451118,0.182325,0.560039,0.464108,0.814875,1.000000

In [43]:
def get_similar(question, rating):
    similar_ratings = corrMatrix[question] * (rating - 2.5)
    similar_ratings = similar_ratings.sort_values(ascending=False)
    return similar_ratings

In [44]:
c1 = "Bachelor of Science in Civil Engineering"
c2 = "Bachelor of Science in Electrical Engineering"
c3 = "Bachelor of Science in Information Technology"
c4 = "Bachelor of Science in Computer Science"
c5 = "Bachelor of Science in Library and Information Science"
c6 = "Bachelor of Science in Accountancy"
c7 = "Bachelor of Science in Management Accounting"
c8 = "Bachelor of Science in internal Auditing"
c9 = "Bachelor of Science in Business Administration"
c10 = "Bachelor of Science in Psychology"
c11 = "Bachelor of Physical Education"
c12 = "Bachelor of Elementary Education"
c13 = "Bachelor of Secondary Education"
c14 = "Bachelor of Special Needs Education"
c15 = "Bachelor in Human Needs"
c16 = "Bachelor of Science in Hospital Management"
c17 = "Bachelor of Science in Nursing"
q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17 = 5,4,3,3,3,4,2,3,2,3,1,2,2,1,1,1,1

ratings = [(c1, q1), (c2, q2), (c3, q3), (c4, q4), (c5, q5), (c6, q6), (c7, q7), (c8, q8), (c9, q9), (c10, q10),
           (c11, q11), (c12, q12), (c13, q13), (c14, q14), (c15, q15), (c16, q16), (c17, q17)]

In [45]:
similar = pd.DataFrame(get_similar(question, rating))

for question, rating in ratings:
#      similar=similar.append(get_similar(question, rating), ignore_index=True)
     similarDf = pd.concat([similarDf,similar])
     similar.head(10)

similar.sum().sort_values(ascending=False).head(3)

NameError: name 'similarDf' is not defined